### ISSUE TITLE
Adding Chrome PR

### ISSUE THREAD

**Issue by julioflima** [accetto/xubuntu-vnc-novnc#3]
Hi, first I'd like be grateful about this project. That solved my life.

But I couldn't install any extension in Chromium, was unstable even in Chrome Web Store, crashing after search any extension.

So, I achieve install Chrome in it, and even install extensions by terminal. 

**So I'd like to contribute adding Chrome as a possibility.**

Until this moment I just not added yet the Chrome in Desktop, but was running nicely.

If you like the idea, I could send a **PR** with modifications and the readme most likely your pattern instructing about the Chrome.

**Comment by accetto** [comment]
Hi juloko,

you're welcome, your contribution will be appreciated. :-) I'm really unable to find more time for Chromium.

Currently I'm concentrating on a new generation of images, based on Ubuntu 20.04 LTS. There is even bigger problem with Chromium, because it's dependent on **snap**, which doesn't seem to work correctly in Docker. So I have to install Chromium for Ubuntu 18.04, which is not ideal. Maybe your approach will work better also for Ubuntu 20.04.

Cheers,
accetto

**Comment by julioflima** [comment]
I'm having a lot of trouble with old Ubuntu so, Ubuntu 20.04 LTS gonna be so welcome.

________________________________
De: accetto <notifications@github.com>
Enviado: terça-feira, 27 de outubro de 2020 11:37
Para: accetto/xubuntu-vnc-novnc <xubuntu-vnc-novnc@noreply.github.com>
Cc: Julio Lima <julio_flima@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [accetto/xubuntu-vnc-novnc] Adding Chrome PR (#3)


Hi juloko,

you're welcome, your contribution will be appreciated. :-) I'm really unable to find more time for Chromium.

Currently I'm concentrating on a new generation of images, based on Ubuntu 20.04 LTS. There is even bigger problem with Chromium, because it's dependent on snap, which doesn't seem to work correctly in Docker. So I have to install Chromium for Ubuntu 18.04, which is not ideal. Maybe your approach will work better also for Ubuntu 20.04.

Cheers,
accetto

**Comment by accetto** [comment]
Feel free to send your PR. The new repository based on Ubuntu 20.04 is not ready yet, it will still take some time.

**Comment by julioflima** [comment]
I've started to modify. Follow the link in below and the progress. Gonna be awesome if you could check the diff. Follow the link in below:
https://github.com/juloko/xubuntu-vnc-novnc

**Things done:**
- Changed every word Chromium to Chrome.
- Added the script to install chrome.

**Missing to do:**
- Test! :|
- After test add the image with chrome running in xubuntu. 
- Add script to kill process, p-kill don't work with Chrome.

**Doubts:**
- I don't know what that script chromium `chrome-browser.init` in `Dockerfile.chrome` does.
- I have a script to install extentions to chrome, maybe should be good to testers, I don't know if I should add.
- How we should proceed in this project with a fork or branches?
- You should creat the project `ubuntu-vnc-xfce-chrome` like the others?

**Comment by accetto** [comment]
Thanks for the post. I'll try to check it over the weekend.
Btw, I'm thinking about merging the `ubuntu-vnc-xfce...` repositories to one single repository again. How do you find the idea?

**Comment by accetto** [comment]
Sorry, I didn't made it. I'll still need a few more days. Btw, could you send it as a standard pull request?

**Comment by julioflima** [comment]
I still need too. But I gonna do.

**Comment by accetto** [comment]
Hello @juloko,

I've just released a new generation of containers based on **Ubuntu 20.04 LTS**. You can find it on [GitHub](https://github.com/accetto/ubuntu-vnc-xfce-g3).

The containers with Chromium Browser are in [this repository](https://hub.docker.com/repository/docker/accetto/ubuntu-vnc-xfce-chromium-g3) on Docker Hub. I had to use the Chromium version for Ubuntu 18.04, because the one for Ubuntu 20.04 depends on **snap**, which doesn's work in containers, but it seems to be all right. I was able to install also extensions, at least a few ones I've tried.

So have a look and let me know if it works for you.

Regards,
@accetto

**Comment by accetto** [comment]
Seems like this is idle, so I'll close it. It can be re-opened any time.

**Comment by julioflima** [comment]
Thanks for maintaining, I didn't have any more time. Seams working on Xubuntu, in future I'll test the Ubuntu version.

**Comment by accetto** [comment]
Hello @julioflima 
I've released a new image with Chrome at last. You can check it at [accetto/xubuntu-vnc-novnc-chrome](https://hub.docker.com/r/accetto/xubuntu-vnc-novnc-chrome).
Regards, accetto
